<?php

namespace App\Policies;

use App\Models\User;
use App\Models\Invoice;

class InvoicePolicy
{
    /**
     * Determine if the user can view any invoices.
     * Only Owners can view invoices.
     */
    public function viewAny(User $user)
    {
        return $user->isOwner();
    }

    /**
     * Determine if the user can view the invoice.
     * Only Owners can view invoices.
     */
    public function view(User $user, Invoice $invoice)
    {
        return $user->isOwner();
    }

    /**
     * Determine if the user can create invoices.
     * NO ONE can manually create invoices - they are auto-generated by the system only.
     */
    public function create(User $user)
    {
        return false; // Manual invoice creation is strictly prohibited
    }

    /**
     * Determine if the user can update the invoice.
     * Only Owners can mark invoices as paid.
     */
    public function update(User $user, Invoice $invoice)
    {
        return $user->isOwner();
    }

    /**
     * Determine if the user can delete the invoice.
     * Only Owners can delete invoices.
     */
    public function delete(User $user, Invoice $invoice)
    {
        return $user->isOwner();
    }
}
