<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\InvoiceService;
use App\Models\Invoice;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;

class InvoiceController extends Controller
{
    private $invoiceService;

    public function __construct(InvoiceService $invoiceService)
    {
        $this->invoiceService = $invoiceService;
    }

    public function all(Request $request)
    {
        $this->authorize('viewAny', Invoice::class);
        
        $invoices = $this->invoiceService->getAllInvoices();

        return response()->json([
            'success' => true,
            'data' => $invoices
        ]);
    }

    public function index(Request $request, $projectId)
    {
        $this->authorize('viewAny', Invoice::class);
        
        $invoices = $this->invoiceService->getInvoicesByProject($projectId);

        return response()->json([
            'success' => true,
            'data' => $invoices
        ]);
    }

    public function store(Request $request)
    {
        // Manual invoice creation is strictly prohibited
        // Invoices are auto-generated by the system only
        return response()->json([
            'success' => false,
            'message' => 'Manual invoice creation is not allowed. Invoices are auto-generated when DPRs are approved.'
        ], 403);
    }

    public function show($id)
    {
        $invoice = Invoice::with(['project', 'items', 'task', 'dpr'])->findOrFail($id);
        $this->authorize('view', $invoice);

        return response()->json([
            'success' => true,
            'data' => $invoice
        ]);
    }

    public function markAsPaid(Request $request, $id)
    {
        $invoice = Invoice::findOrFail($id);
        $this->authorize('update', $invoice);
        
        try {
            $invoice = $this->invoiceService->markAsPaid($id);

            return response()->json([
                'success' => true,
                'message' => 'Invoice marked as paid',
                'data' => $invoice
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ], 422);
        }
    }

    /**
     * Generate and download PDF for an invoice
     */
    public function generatePdf($id)
    {
        try {
            $invoice = Invoice::with(['project', 'items'])->findOrFail($id);

            // Create PDF content
            $html = view('invoices.pdf', compact('invoice'))->render();
            
            $pdf = Pdf::loadHTML($html)
                ->setPaper('a4')
                ->setOption('margin-top', 10)
                ->setOption('margin-bottom', 10)
                ->setOption('margin-left', 10)
                ->setOption('margin-right', 10);

            $fileName = 'invoice_' . $invoice->id . '_' . now()->format('Y-m-d') . '.pdf';

            return $pdf->download($fileName);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to generate PDF: ' . $e->getMessage()
            ], 422);
        }
    }

    /**
     * Stream PDF for viewing in browser
     */
    public function viewPdf($id)
    {
        try {
            $invoice = Invoice::with(['project', 'items'])->findOrFail($id);

            // Create PDF content
            $html = view('invoices.pdf', compact('invoice'))->render();
            
            $pdf = Pdf::loadHTML($html)
                ->setPaper('a4')
                ->setOption('margin-top', 10)
                ->setOption('margin-bottom', 10)
                ->setOption('margin-left', 10)
                ->setOption('margin-right', 10);

            return $pdf->stream();
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to view PDF: ' . $e->getMessage()
            ], 422);
        }
    }
}
